In [ ]:
import pandas as pd
import numpy as np
col_names=[]
x=[]
y=[]
p=[]
for i in range(16):
    x.append(f"X{i}")
    y.append(f"Y{i}")
    p.append(f"P{i}")

col_names.append(x)
col_names.append(y)
col_names.append(p)

flat_list = [item for sublist in col_names for item in sublist]
flat_list.append("PALL")
print(flat_list)

['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9', 'Y10', 'Y11', 'Y12', 'Y13', 'Y14', 'Y15', 'P0', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'PALL']


In [ ]:
adelaide = pd.read_csv('/work/WOC/Adelaide_Data.csv', names = flat_list, header=None)
adelaide.head()

X0        X1        X2        X3        X4        X5        X6  \
0  316.5855  223.9277  182.3434  551.5497    7.8641  243.1339  361.0877   
1  530.3136   68.7031   31.5983  175.2582  516.1441   63.4652   67.0954   
2   27.3967  399.0488  565.6854  394.0466  120.2245  558.1293  546.4520   
3  346.1526   59.6375  226.2742  280.9095  402.2161  218.7181  207.0407   
4  317.9144  551.8542  335.4745   40.0240  316.6285  365.6434  416.3060   

         X7        X8        X9  ...          P7          P8          P9  \
0  115.9284   78.6087  468.3799  ...  82322.0277  98069.1011  86578.6330   
1  369.4486   14.0930  375.4462  ...  83920.1033  80968.0044  87108.1328   
2   27.3256  314.1051  235.9476  ...  97358.7395  93437.7170  69940.2554   
3  339.5676    0.0000    0.0000  ...  80399.3841  89349.6141  85048.3860   
4  562.1028  211.3577  143.1255  ...  97088.1761  81187.3982  63591.6729   

          P10         P11         P12         P13         P14         P15  \
0  93016.4133  63145.1829  98353.1952  80225.1390  98447.2846  97570.2225   
1  68065.1856  99061.3812  77549.1426  99013.1628  78234.4337  84633.6493   
2  92864.1192  60887.8095  72306.6556  81151.1515  83030.9726  94779.6131   
3  70038.2271  92797.3569  97653.8121  74903.3740  71690.6549  96220.4768   
4  92418.1977  82454.8256  97091.7749  85937.5437  66823.1572  93683.0996   

          PALL  
0  1370374.145  
1  1340929.765  
2  1352031.511  
3  1396754.375  
4  1355708.577  

[5 rows x 49 columns]

In [ ]:
adelaide2 = adelaide.iloc[:, 0:32]
adelaide2.head()

X0        X1        X2        X3        X4        X5        X6  \
0  316.5855  223.9277  182.3434  551.5497    7.8641  243.1339  361.0877   
1  530.3136   68.7031   31.5983  175.2582  516.1441   63.4652   67.0954   
2   27.3967  399.0488  565.6854  394.0466  120.2245  558.1293  546.4520   
3  346.1526   59.6375  226.2742  280.9095  402.2161  218.7181  207.0407   
4  317.9144  551.8542  335.4745   40.0240  316.6285  365.6434  416.3060   

         X7        X8        X9  ...        Y6        Y7        Y8        Y9  \
0  115.9284   78.6087  468.3799  ...  247.9875  269.9356  495.7867  105.5203   
1  369.4486   14.0930  375.4462  ...  107.3907  248.7212  415.6457  410.1439   
2   27.3256  314.1051  235.9476  ...  516.1118  498.6277  435.2397   35.5588   
3  339.5676    0.0000    0.0000  ...  176.7005  217.2239  562.7245  347.2173   
4  562.1028  211.3577  143.1255  ...  337.7052  536.6741  143.3888   48.6452   

        Y10       Y11       Y12       Y13       Y14       Y15  
0  141.8014   18.7857  496.6488    3.2835  513.9628  105.5529  
1  156.3712  532.9900  280.7516  559.2803  208.7441  531.3943  
2  148.9206   48.0585  317.9832   26.8732  483.0186  359.0875  
3    0.0000  272.3906  178.4930  317.5044  235.5983   19.6762  
4  109.5254  377.3113  530.8384  463.1129   42.6895  367.9045  

[5 rows x 32 columns]

In [ ]:
data_point1 = np.array([adelaide2.iloc[48393]])
data_point2 = adelaide2.iloc[3458]
data_point3 = adelaide2.iloc[13864]

In [ ]:
# Features matrix
X = adelaide.iloc[:, 0:32]
X = X.values

# label vector
y = adelaide["PALL"]
y = y.values

X.shape

(71999, 32)

# Applichiamo l'algoritmo con scikit learn

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(adelaide.iloc[:, 0:32], adelaide['PALL'], random_state=0)

In [ ]:
print("Lunghezza dataset training:",len(X_train))
print("Lunghezza target training:",len(y_train))
print("Lunghezza dataset test:",len(X_test))
print("Lunghezza target test:",len(y_test))

Lunghezza dataset training: 53999
Lunghezza target training: 53999
Lunghezza dataset test: 18000
Lunghezza target test: 18000


In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
model_M1 = KNeighborsRegressor(n_neighbors=5, metric='manhattan')
model_M2 = KNeighborsRegressor(n_neighbors=269, metric='manhattan')

In [ ]:
model_E1 = KNeighborsRegressor(n_neighbors=5, metric='euclidean')
model_E2 = KNeighborsRegressor(n_neighbors=269, metric='euclidean')

In [ ]:
model_K1 = KNeighborsRegressor(n_neighbors=5, metric='minkowski')
model_K2 = KNeighborsRegressor(n_neighbors=269, metric='minkowski')

In [ ]:
model_M1.fit(X_train, y_train)
model_M2.fit(X_train, y_train)

model_E1.fit(X_train, y_train)
model_E2.fit(X_train, y_train)

model_K1.fit(X_train, y_train)
model_K2.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=269)

In [ ]:
model_M1.predict(data_point1)
model_M2.predict(data_point1)

model_E1.predict(data_point1)
model_E2.predict(data_point1)

model_K1.predict(data_point1)
model_K2.predict(data_point1)

print('secondo il modello M1 PALL di data_point1 è: ', model_M1.predict(data_point1))
print('secondo il modello M2 PALL di data_point1 è: ', model_M2.predict(data_point1))
print('secondo il modello E1 PALL di data_point1 è: ', model_E1.predict(data_point1))
print('secondo il modello E2 PALL di data_point1 è: ', model_E2.predict(data_point1))
print('secondo il modello K1 PALL di data_point1 è: ', model_K1.predict(data_point1))
print('secondo il modello K2 PALL di data_point1 è: ', model_K2.predict(data_point1))

secondo il modello M1 PALL di data_point1 è:  [1410417.2684]
secondo il modello M2 PALL di data_point1 è:  [1430340.81182528]
secondo il modello E1 PALL di data_point1 è:  [1411640.1184]
secondo il modello E2 PALL di data_point1 è:  [1430902.99832714]
secondo il modello K1 PALL di data_point1 è:  [1411640.1184]
secondo il modello K2 PALL di data_point1 è:  [1430902.99832714]
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature n

In [ ]:
perc_prec = model_M1.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo M1: {(perc_prec.round(2))}%")

perc_prec = model_M2.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo M2: {(perc_prec.round(2))}%")

Percentuale di precisione dell'Algoritmo M1: 81.15%
Percentuale di precisione dell'Algoritmo M2: 69.79%


In [ ]:
perc_prec = model_E1.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo E1: {(perc_prec.round(2))}%")

perc_prec = model_E2.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo E2: {(perc_prec.round(2))}%")

Percentuale di precisione dell'Algoritmo E1: 79.15%
Percentuale di precisione dell'Algoritmo E2: 71.25%


In [ ]:
perc_prec = model_K1.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo K1: {(perc_prec.round(2))}%")

perc_prec = model_K2.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo K2: {(perc_prec.round(2))}%")

Percentuale di precisione dell'Algoritmo K1: 79.15%
Percentuale di precisione dell'Algoritmo K2: 71.25%


# Osservazioni

1 - calcolando le distanze manualmente, non ci sono grosse differenze di tempo fra distanza euclidea e distanza coseno

2 - scikit learn non ha fra le metriche la distanza coseno

3 - a livello di performance, Manhattan sembra essere più preciso, ma su deepnote hanno fatto acc.90%, perchè?

4 - ci vuole più tempo a fare il test che a fare .predict

5 - più è piccolo k, più sembra accurato il modello

Controlliamo il tempo di esecuzione dei vari modelli

In [ ]:
%%time
model_M1 = KNeighborsRegressor(n_neighbors=5, weights="distance", metric='manhattan')
model_M1.fit(X_train, y_train)
model_M1.predict(data_point1)

CPU times: user 14 ms, sys: 190 µs, total: 14.1 ms
Wall time: 13.8 ms
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([1407396.486])

In [ ]:
%%time
model_M1 = KNeighborsRegressor(n_neighbors=5, weights="distance", metric='manhattan')
model_M1.fit(X_train, y_train)
model_M1.predict(data_point1)
perc_prec = model_M1.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo M1: {(perc_prec.round(2))}%")

/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"
Percentuale di precisione dell'Algoritmo M1: 81.6%
CPU times: user 1min 22s, sys: 2.02 s, total: 1min 24s
Wall time: 1min 24s


In [ ]:
%%time
model_E1 = KNeighborsRegressor(n_neighbors=5, weights="distance", metric='euclidean')
model_E1.fit(X_train, y_train)
model_E1.predict(data_point1)

CPU times: user 14.1 ms, sys: 4.63 ms, total: 18.8 ms
Wall time: 14.8 ms
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([1407396.486])

In [ ]:
%%time
model_E1 = KNeighborsRegressor(n_neighbors=5, weights="distance", metric='euclidean')
model_E1.fit(X_train, y_train)
model_E1.predict(data_point1)
perc_prec = model_E1.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo E1: {(perc_prec.round(2))}%")

/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"
Percentuale di precisione dell'Algoritmo E1: 79.55%
CPU times: user 26.9 s, sys: 3.78 s, total: 30.6 s
Wall time: 26.5 s


In [ ]:
%%time
model_K1 = KNeighborsRegressor(n_neighbors=5, weights="distance", metric='minkowski')
model_K1.fit(X_train, y_train)
model_K1.predict(data_point1)

CPU times: user 158 ms, sys: 133 µs, total: 158 ms
Wall time: 156 ms
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([1407396.486])

In [ ]:
%%time
model_K1 = KNeighborsRegressor(n_neighbors=5,  weights="distance", metric='minkowski')
model_K1.fit(X_train, y_train)
model_K1.predict(data_point1)
perc_prec = model_K1.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo K1: {(perc_prec.round(2))}%")

/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"


KeyboardInterrupt: 

In [ ]:
%%time
model_C1 = KNeighborsRegressor(n_neighbors=5,  weights="distance", metric='cosine')
model_C1.fit(X_train, y_train)
model_C1.predict(data_point1)

CPU times: user 11.6 ms, sys: 12.2 ms, total: 23.8 ms
Wall time: 19.7 ms
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([1407396.486])

In [ ]:
%%time
model_C1 = KNeighborsRegressor(n_neighbors=5,  weights="distance", metric='cosine')
model_C1.fit(X_train, y_train)
model_C1.predict(data_point1)
perc_prec = model_C1.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo C1: {(perc_prec.round(2))}%")

/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"
Percentuale di precisione dell'Algoritmo C1: 79.87%
CPU times: user 25.9 s, sys: 3.81 s, total: 29.7 s
Wall time: 26.7 s


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=531276df-e637-43fd-b6d2-ed5088148a23' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>