In [1]:
# Start writing code here...

### ESERCIZIO 1
# I imported data for you. Your are welcome! 🙂
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

data = load_iris()

X = data['data']
y = data['target']

print(f"Dataset is made by {len(X)} data, whose first 5 lines are \n {X[:5]} \n ")
print(f"Target vector is {len(y)}-long, and targets names are \n {data['target_names']}")
data

Dataset is made by 150 data, whose first 5 lines are 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 
 
Target vector is 150-long, and targets names are 
 ['setosa' 'versicolor' 'virginica']


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [2]:
df = pd.DataFrame(data['data'], columns = ["S-L","S-W","P-L","P-W"])
df["Specie"] = y # Aggiungo la specie
df.sort_values("Specie") # Ordino in ordine crescente la specie 0-setosa, 1-versicolor, 2-virginica
# Il dizionario y era già ordinato ma è questione di pulizia e corretta procedura.
df.head()

S-L  S-W  P-L  P-W  Specie
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

In [3]:
#Copio quanto fa Oscar, quindi ritogliamo la specie, e da Dataframe lo fa tornare un array numpy
#Il che significa che la cella sopra, per ora, è lì solo per la visualizzazione e controllo dei dati

# Features matrix
X = df.drop("Specie", axis=1)
X = X.values

# label vector
y = df["Specie"]
y = y.values

In [4]:
#Creo un Campione e un Test di 10 elementi

import random

#Uso ciclo While per evitare ripetizioni degli indici da eliminare

l1 = []
while len(l1) < 10:
    rand = random.randint(0,149)
    if rand in l1:
        continue
    else:
        l1.append(rand)

camp = np.delete(X,l1,axis=0)
test = X[l1]
soluzione = y[l1]
Y_camp = np.delete(y,l1,axis=0).reshape(140,1)

print(l1) # Dovrei avere 10 valori da 0 a 149 tutti diversi tra loro
print(X.shape) # La matrice di origine con 150 elementi
print(camp.shape) # La matrice Campione con 140 elementi
print(test.shape) # La matrice Test con 10 elementi
print(soluzione) # i risultati che dovranno combaciare con la nostra previsione 

[82, 116, 122, 5, 8, 53, 23, 99, 70, 38]
(150, 4)
(140, 4)
(10, 4)
[1 2 2 0 0 1 0 1 1 0]


In [6]:
def euclidean_distance(x, y):
    """Euclidean distance implementation.
    Parameters
    ----------
    x, y: np.array
    Return
    ------
    float: the Euclidean distance between x, y.
    """
    return np.linalg.norm(x-y, axis=1) 

def cosine_distance(x, y):
    """Cosine distance implementation.

    Parameters
    ----------
    x, y: np.array

    Return
    ------
    float: the Cosine distance between x, y.
    """
    return np.abs(np.dot(x, y))/(np.linalg.norm(x) * np.linalg.norm(y))

def manhattan_distance(x, y):
    """Manhattan distance implementation.

    Parameters
    ----------
    x, y: np.array

    Return
    ------
    float: the Manhattan distance between x, y.
    """
    return np.sum(np.abs(x-y))



In [7]:
%%time 
# Dopo aver pulito e sistemato i dati
# Qui inizia il vero modello
# Quindi qui calcoliamo il tempo di produzione dello stesso.

matrix = np.zeros((140, 1))
for row in test:
    dis1 = euclidean_distance(camp,row)
    dis_array1 = np.array(dis1).reshape(140,1)
    matrix = np.concatenate((matrix, dis_array1),axis=1)

matrix = np.delete(matrix,0,axis=1)
print(matrix.shape) # Deve essere 140,10, dove 10 sono le dieci osservazioni test.
print(matrix[:5,:5])

(140, 10)
[[2.89482297 4.64542786 6.21128006 0.6164414  0.92195445]
 [2.85482048 4.68294779 6.26178888 1.09087121 0.50990195]
 [3.03644529 4.84561658 6.44670458 1.08627805 0.43588989]
 [2.89136646 4.70956474 6.32297398 1.16619038 0.3       ]
 [2.94957624 4.68828327 6.26578008 0.6164414  0.92195445]]
CPU times: user 2.46 ms, sys: 0 ns, total: 2.46 ms
Wall time: 2.57 ms


In [8]:
#kNN

k = 6

#Troviamo la matrice degli indici

matrix_ind = np.zeros((6, 1))

for col in range(10):
    nn_id = np.array(matrix[:,col].argsort()[:k]).reshape(6,1)
    matrix_ind = np.concatenate((matrix_ind, nn_id),axis=1)

matrix_ind = np.delete(matrix_ind,0,axis=1)

df_ind = pd.DataFrame(matrix_ind)
df_ind

0      1      2     3     4     5     6     7      8     9
0  85.0  127.0   97.0  16.0   3.0  82.0  23.0  89.0  128.0  38.0
1  62.0   95.0  109.0   8.0  38.0  74.0  39.0  87.0  117.0  11.0
2  64.0  137.0   99.0  44.0  11.0  64.0  35.0  81.0  139.0   3.0
3  65.0  103.0  120.0  40.0  43.0  75.0   6.0  88.0   78.0  43.0
4  87.0  118.0  125.0  42.0  41.0  85.0  28.0  85.0   51.0   2.0
5  82.0  104.0  115.0  17.0  10.0  87.0  15.0  62.0  116.0  41.0

In [9]:
#Troviamo la matrice delle distanze
matrix_dis = np.zeros((6, 1))


for col in range(10):
    index_col = matrix_ind[:,col].astype(int)
    nn_dis = np.array(matrix[index_col,col]).reshape(6,1)
    matrix_dis = np.concatenate((matrix_dis, nn_dis),axis=1)

matrix_dis = np.delete(matrix_dis,0,axis=1)

df_dis = pd.DataFrame(matrix_dis)
df_dis

0         1         2         3         4         5         6  \
0  0.141421  0.141421  0.264575  0.331662  0.300000  0.200000  0.200000   
1  0.282843  0.244949  0.412311  0.346410  0.316228  0.300000  0.264575   
2  0.300000  0.360555  0.608276  0.360555  0.346410  0.316228  0.374166   
3  0.346410  0.387298  0.678233  0.374166  0.360555  0.435890  0.387298   
4  0.374166  0.387298  0.700000  0.387298  0.424264  0.435890  0.387298   
5  0.387298  0.424264  0.969536  0.387298  0.424264  0.458258  0.412311   

          7         8         9  
0  0.141421  0.223607  0.200000  
1  0.173205  0.300000  0.244949  
2  0.223607  0.360555  0.300000  
3  0.244949  0.424264  0.300000  
4  0.264575  0.469042  0.360555  
5  0.331662  0.500000  0.424264

In [10]:
#Valori della variabile risposta
matrix_y = np.zeros((6, 1))

for col in range(10):
    index_col2 = matrix_ind[:,col].astype(int).reshape(6,1)
    matrix_y = np.concatenate((matrix_y, Y_camp[index_col2,0]),axis=1)

matrix_y = np.delete(matrix_y,0,axis=1)
df_y = pd.DataFrame(matrix_y)
df_y

0    1    2    3    4    5    6    7    8    9
0  1.0  2.0  2.0  0.0  0.0  1.0  0.0  1.0  2.0  0.0
1  1.0  2.0  2.0  0.0  0.0  1.0  0.0  1.0  2.0  0.0
2  1.0  2.0  2.0  0.0  0.0  1.0  0.0  1.0  2.0  0.0
3  1.0  2.0  2.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0
4  1.0  2.0  2.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0
5  1.0  2.0  2.0  0.0  0.0  1.0  0.0  1.0  2.0  0.0

In [11]:
matrix_pred = np.zeros((3, 1))

Setosa = []

Versicolor= []

Virginica = []

 
for col in range(10):
    a1 = []
    a2 = []
    a3 = []

    for row in range (6):

        if matrix_y[row,col] == 0:
            a1.append(matrix_dis[row,col])
        elif matrix_y[row,col] == 1:
            a2.append(matrix_dis[row,col])
        else:
            a3.append(matrix_dis[row,col])

    Setosa.append(sum(a1))
    Versicolor.append(sum(a2))
    Virginica.append(sum(a3))         

print(Setosa, len(Setosa))
print(Versicolor, len(Versicolor))
print(Virginica, len(Virginica))

[0, 0, 0, 2.1873901760145933, 2.1717211925008684, 0, 2.025648101587103, 0, 0, 1.8297681705366444] 10
[1.83213830352384, 0, 0, 0, 0, 2.146265124220557, 0, 1.3794198191644942, 0.8933056446942705, 0] 10
[0, 1.9457861960154377, 3.6329309164938417, 0, 0, 0, 0, 0, 1.384161925296378, 0] 10


In [12]:
Set_len=[]
Ver_len=[]
Vir_len=[]

for col in range(10):
    a1 = []
    a2 = []
    a3 = []
    for row in range (6):
        if matrix_y[row,col] == 0:
            a1.append(1)
        elif matrix_y[row,col] == 1:
            a2.append(1)
        else:
            a3.append(1)

    Set_len.append(sum(a1))
    Ver_len.append(sum(a2))
    Vir_len.append(sum(a3))  

print(Set_len)
print(Ver_len)
print(Vir_len)

[0, 0, 0, 6, 6, 0, 6, 0, 0, 6]
[6, 0, 0, 0, 0, 6, 0, 6, 2, 0]
[0, 6, 6, 0, 0, 0, 0, 0, 4, 0]


In [13]:
# Matrice poi if se != 0 per la divisione
# Poi ottengo una matrice finale, metto i valori nulli, e gli altri valori per ogni colonna trovo il minimo e quindi mi trovo un vettore di risultato
matrix_unione= np.array([Set_len,Ver_len,Vir_len])
matrix_unione1= np.array([Setosa,Versicolor,Virginica])

matrix_fin = np.zeros((3,10))

for col in range(10):
    for row in range(3):
        if matrix_unione[row,col] != 0:
            matrix_fin[row,col] = matrix_unione1[row,col]/matrix_unione[row,col]
        else:
            matrix_fin[row,col] = np.nan


df_fin =pd.DataFrame(matrix_fin,index=["Setosa","Versicolor","Virginica"])




In [14]:
list_finale = []
for col in range(10):
    list_finale.append(matrix_fin[:,col].argsort()[0])

print("Soluzione: ",soluzione)
print("Predizione: ",list_finale)

errori=[]

if list(soluzione) == list_finale:
    print("il modello è perfetto")
else:
    for x in range(10):
        if list(soluzione)[x] != list_finale[x]:
            errori.append(1)
            print("Errore al test numero: ", x+1)

    print(f"Il modello ha {sum(errori)} errore su 10")

Soluzione:  [1 2 2 0 0 1 0 1 1 0]
Predizione:  [1, 2, 2, 0, 0, 1, 0, 1, 2, 0]
Errore al test numero:  9
Il modello ha 1 errore su 10


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=61b6c287-bc7c-4276-9bde-4e2cd887687b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>