Use  𝑘 NN just implemented to solve a classification problem. (e.g. the notorious Iris classification problem).

In [ ]:
# I imported data for you. Your are welcome! 🙂
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

iris = load_iris()

X = iris['data']
y = iris['target']

print(f"Dataset is made by {len(X)} data, whose first 5 lines are \n {X[:5]} \n ")
print(f"Target vector is {len(y)}-long, and targets names are \n {iris['target_names']}")

Dataset is made by 150 data, whose first 5 lines are 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 
 
Target vector is 150-long, and targets names are 
 ['setosa' 'versicolor' 'virginica']


Possiamo scegliere K come radice quadrata del numero di tutti i casi nel nostro set di dati K = Sqrt (n) quindi scegliere il valore Dispari più vicino ad esso per evitare confusione tra due classi di dati (i valori dispari ci consentono avere anche un "vicino di casa in parità").

In [ ]:
# Split the data set into training and testing
# train_test_split è una funzione che divide il dataset in 75% di date per il taining e il 25% dei dati per testare)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=0)

#Random seed used to initialize the pseudo-random number generator. Can be any integer between 0 and 2**32 - 1

In [ ]:
print("Lunchezza dataset di training:",len(X_train))
print("Lunchezza target di training:",len(y_train))
print("Lunchezza dataset di test:",len(X_test))
print("Lunchezza target di test:",len(y_test))

Lunchezza dataset di training: 112
Lunchezza target di training: 112
Lunchezza dataset di test: 38
Lunchezza target di test: 38


In [ ]:
# Usiamo sklearn  per chiamare KneighborsClassifier con K = 1 (n_neighbors). 
#La funzione di adattamento ci consente di memorizzare il nostro dataset di dati di allenamento.

from sklearn.neighbors import KNeighborsClassifier
#calcoliamo la radice quadra di 150 e consideriamo il numero dispari
KNN_Classifier = KNeighborsClassifier(n_neighbors=11) 

KNN_Classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=11)

In [ ]:
#testiamo l'algoritmo con un fiore dai dati casuali

X_newIris = np.array([[5.2, 3.4, 1.7, 0.6]])

predictNew = KNN_Classifier.predict(X_newIris)
print(predictNew)


[0]


In [ ]:
#controllo percentuale precisione dell'algoritmo
perc_prec = KNN_Classifier.score(X_test, y_test)*100
print(f"Percentuale di precisione dell'Algoritmo: {(perc_prec.round(2))}%")

Percentuale di precisione dell'Algoritmo: 97.37%


In [ ]:
print (KNN_Classifier.get_params(deep=True))

{'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 11, 'p': 2, 'weights': 'uniform'}


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=61b6c287-bc7c-4276-9bde-4e2cd887687b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>