In [1]:
### ESERCIZIO 1
# I imported data for you. Your are welcome! 🙂
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

data = load_iris()

X = data['data']
y = data['target']

print(f"Dataset is made by {len(X)} data, whose first 5 lines are \n {X[:5]} \n ")
print(f"Target vector is {len(y)}-long, and targets names are \n {data['target_names']}")
data

Dataset is made by 150 data, whose first 5 lines are 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 
 
Target vector is 150-long, and targets names are 
 ['setosa' 'versicolor' 'virginica']


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [2]:
df = pd.DataFrame(data['data'], columns= ["S-L","S-W","P-L","P-W"])
df["Specie"] = y
df.sort_values("Specie")
df.head()

S-L  S-W  P-L  P-W  Specie
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

In [3]:
def euclidean_distance(x, y):
    """Euclidean distance implementation.
    Parameters
    ----------
    x, y: np.array
    Return
    ------
    float: the Euclidean distance between x, y.
    """
    return np.linalg.norm(x-y, axis=1)

def cosine_distance(x, y):
    """Cosine distance implementation.

    Parameters
    ----------
    x, y: np.array

    Return
    ------
    float: the Cosine distance between x, y.
    """
    return np.abs(np.dot(x, y))/(np.linalg.norm(x) * np.linalg.norm(y))

def manhattan_distance(x, y):
    """Manhattan distance implementation.

    Parameters
    ----------
    x, y: np.array

    Return
    ------
    float: the Manhattan distance between x, y.
    """
    return np.sum(np.abs(x-y))



In [4]:
# Features matrix
X = df.drop("Specie", axis=1)
X = X.values

# label vector
y = df["Specie"]
y = y.values

In [5]:
l = []
for i in range(10):
    l.append(np.random.randint(0,149))

X_campione = np.delete(X,l,0)
X_test = X[l]

In [6]:
# MODELLO MEDIA 
# SCELGO I DATI CAMPIONE E I DATI TEST
import random

l1 = []
while len(l1) < 10:
    rand = random.randint(0,149)
    if rand in l1:
        continue
    else:
        l1.append(rand)

df_campione = df.drop(index = l1)
df_test = df.iloc[l1].drop("Specie",axis=1)

print(l1)

[74, 30, 77, 148, 11, 83, 73, 129, 15, 110]


In [7]:
%%time

#CREAZIONE DEL MODELLO

df_set = df_campione[df_campione["Specie"] == 0].drop("Specie",axis=1)
df_ver = df_campione[df_campione["Specie"] == 1].drop("Specie",axis=1)
df_vig = df_campione[df_campione["Specie"] == 2].drop("Specie",axis=1)

mean_set = np.array([df_set.mean(axis='index')])
mean_ver = np.array([df_ver.mean(axis='index')])
mean_vig = np.array([df_vig.mean(axis='index')])
matrix_mean = np.concatenate((mean_set,mean_ver,mean_vig),axis=0)

D_set=euclidean_distance(df_test,mean_set).reshape([10,1])
D_ver=euclidean_distance(df_test,mean_ver).reshape([10,1])
D_vig=euclidean_distance(df_test,mean_vig).reshape([10,1])
D_matrix = np.concatenate((D_set,D_ver,D_vig), axis=1)

D_df = pd.DataFrame(D_matrix, columns= ["Setosa","Versicolor","Virginica"])
D_df['Valore minimo']=(D_df.min(1))

List_result1 = []
List_result2 = []
Setosa = "Setosa"
Versicolor= "Versicolor"
Virginica ="Virginica"

for index, row in D_df.iterrows():
    if row["Setosa"] == row["Valore minimo"]:
        List_result1.append(Setosa)
        List_result2.append(0)
    elif row["Versicolor"] == row["Valore minimo"]:
        List_result1.append(Versicolor)
        List_result2.append(1)
    else:
        List_result1.append(Virginica)
        List_result2.append(2)

Wall time: 4.96 ms


In [8]:
# TEST DI CALCOLO
test = np.array(df.iloc[df_test.index]["Specie"]).reshape(10,1)
List_result2_array=np.array(List_result2).reshape(10,1)
List_result2_array

list_control = []

for ind in range(10):
    if test[ind] - List_result2_array[ind] == 0:
        list_control.append(0)

    else:
        list_control.append(1)

if sum(list_control) == 0:
    print("Va tutto bene, il modello funziona!")

else:
    print("Il modello ha qualche errore!")
    print("Numero di errori: ", sum(list_control)," su 10")

print("Test: ",test.reshape(1,10))
print("Modello: ",List_result2_array.reshape(1,10))
print("Controllo:",list_control)

Il modello ha qualche errore!
Numero di errori:  2  su 10
Test:  [[1 0 1 2 0 1 1 2 0 2]]
Modello:  [[1 0 2 2 0 2 1 2 0 2]]
Controllo: [0, 0, 1, 0, 0, 1, 0, 0, 0, 0]


In [9]:
# TEST VISIVO SU TABELLA
D_df["Specie Predetta"] = List_result1
D_df["Predizione Numero"]= List_result2
D_df["Test"]= test
D_check = []
for index, row in D_df.iterrows():
    if row["Predizione Numero"] == row["Test"]:
        D_check.append("Corretto")
    else:
        D_check.append("Sbagliato")
D_df["Check"] = D_check 
D_df

Setosa  Versicolor  Virginica  Valore minimo Specie Predetta  \
0  3.380980    0.521390   1.468649       0.521390      Versicolor   
1  0.402600    3.068582   4.715154       0.402600          Setosa   
2  4.212464    1.205468   0.660846       0.660846       Virginica   
3  4.607067    1.693113   0.663898       0.663898       Virginica   
4  0.251298    3.115826   4.733596       0.251298          Setosa   
5  4.078193    0.936518   0.897582       0.897582       Virginica   
6  3.609527    0.536596   1.299310       0.536596      Versicolor   
7  5.072009    2.080264   0.788828       0.788828       Virginica   
8  1.219244    3.306269   4.689839       1.219244          Setosa   
9  4.319841    1.340709   0.526444       0.526444       Virginica   

   Predizione Numero  Test      Check  
0                  1     1   Corretto  
1                  0     0   Corretto  
2                  2     1  Sbagliato  
3                  2     2   Corretto  
4                  0     0   Corretto  
5                  2     1  Sbagliato  
6                  1     1   Corretto  
7                  2     2   Corretto  
8                  0     0   Corretto  
9                  2     2   Corretto

In [10]:
%%time
#CONTROLLO DELLA PERFORMANCE

lista_controllo = []
n_test = 3000
for tests in range(n_test):
    l1 = []
    while len(l1) < 10:
        rand = random.randint(0,149)
        if rand in l1:
            continue
        else:
            l1.append(rand)
    df_campione = df.drop(index = l1)
    df_test = df.iloc[l1].drop("Specie",axis=1)
    
    df_set = df_campione[df_campione["Specie"] == 0].drop("Specie",axis=1)
    df_ver = df_campione[df_campione["Specie"] == 1].drop("Specie",axis=1)
    df_vig = df_campione[df_campione["Specie"] == 2].drop("Specie",axis=1)
    mean_set = np.array([df_set.mean(axis='index')])
    mean_ver = np.array([df_ver.mean(axis='index')])
    mean_vig = np.array([df_vig.mean(axis='index')])
    matrix_mean = np.concatenate((mean_set,mean_ver,mean_vig),axis=0)
    D_set=euclidean_distance(df_test,mean_set).reshape([10,1])
    D_ver=euclidean_distance(df_test,mean_ver).reshape([10,1])
    D_vig=euclidean_distance(df_test,mean_vig).reshape([10,1])
    D_matrix = np.concatenate((D_set,D_ver,D_vig), axis=1)
    D_df = pd.DataFrame(D_matrix, columns= ["Setosa","Versicolor","Virginica"])
    D_df['Valore minimo']=(D_df.min(1))
    
    List_result1 = []
    List_result2 = []
    Setosa = "Setosa"
    Versicolor= "Versicolor"
    Virginica ="Virginica"

    for index, row in D_df.iterrows():
        if row["Setosa"] == row["Valore minimo"]:
            List_result1.append(Setosa)
            List_result2.append(0)
        elif row["Versicolor"] == row["Valore minimo"]:
            List_result1.append(Versicolor)
            List_result2.append(1)
        else:
            List_result1.append(Virginica)
            List_result2.append(2)
    
    test = np.array(df.iloc[df_test.index]["Specie"]).reshape(10,1)
    List_result2_array=np.array(List_result2).reshape(10,1)
    List_result2_array

    control = test - List_result2_array
    
    
    for ind in range(10):
        if test[ind] - List_result2_array[ind] == 0:
            lista_controllo.append(0)

        else:
            lista_controllo.append(1)

performance = (sum(lista_controllo))/(n_test*10)
print("Test eseguiti: ",len(lista_controllo))
print("Test errati: ",sum(lista_controllo))
print(f"Percentuale errore: {performance} %")

Test eseguiti:  30000
Test errati:  2259
Percentuale errore: 0.0753 %
Wall time: 14.1 s
